- name: install and run nginx
hosts: web
become: yes #it is like -b to get super user
tasKS:
- name: install nginx
ansible.builtin.dnf:
  name: nginx
  state: latest
- name: start nginx
ansible.builtin.service:
  name: nginx
  state: started
  enabled: yes  